name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACK_USERNAME: ${{ secrets.BS_NAME }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_KEY }}
          run: npx wdio run config/wdio.bs.config.js --spec test/specs/classDemo.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
